export const MINAPLAY_PLUGIN_METADATA = 'MINAPLAY_PLUGIN';

export const MINAPLAY_LISTENER_METADATA = 'MINAPLAY_LISTENER_METADATA';

export const MINAPLAY_COMMAND_ARG_METADATA = 'MINAPLAY_COMMAND_ARG';
export const MINAPLAY_COMMAND_METADATA = 'MINAPLAY_COMMAND';
export const PARAMS_METADATA = 'MINAPLAY_PARAMS';

export const MESSAGE_TOKEN = 'MINAPLAY:MESSAGE';
export const PROGRAM_TOKEN = 'MINAPLAY:PROGRAM';
export const PROGRAM_ROOT_TOKEN = 'MINAPLAY:PROGRAM:ROOT';

export const COMMAND_OPTIONS_TOKEN = 'MINAPLAY:COMMAND:OPTIONS';
export const COMMAND_ARGUMENTS_TOKEN = 'MINAPLAY:COMMAND:ARGUMENTS';
